### ISSUE TITLE
Using natbib instead of Pandoc citeproc will throw an error generating bibliography

### ISSUE THREAD

**Issue by cderv** [quarto-journals/jss#1]
I get this error when using `cite-method: natbib`

````
generating bibliography
  This is BibTeX, Version 0.99d (TeX Live 2022)
  The top-level auxiliary file: jss-article.aux
  The style file: jss.bst
  Illegal, another \bibstyle command---line 17 of file jss-article.aux
   : \bibstyle
   :          {plainnat}
  I'm skipping whatever remains of this command
  Database file #1: bibliography.bib
  (There was 1 error message)
````

I believe this is because `jss.cls` is handing the bibliography in this case, So adding triggering `natbib` and default template will activate this lines
https://github.com/quarto-dev/quarto-cli/blob/b7a5449b210302a96952cadb5469dbf30e6db375/src/resources/formats/pdf/pandoc/template.tex#L275-L278

This is the type of thing for which we'll get bitten as we need to identified what to remove from default template, instead of what to add in JSS template. But maybe that would be as difficult. 

Anyway, natbib is not correctly working I think but it could just be a log error as it says 
```
  I'm skipping whatever remains of this command
````
so probably what is provided in `jss.cls` is taken into account

**Comment by dragonstyle** [comment]
There is a `biblio-config` key that you can now set to false to prevent the pandoc template from output the natbib configuration (if the class file is providing that)... Thanks for catching this!

**Comment by cderv** [comment]
For reference, change to extension is in https://github.com/quarto-journals/jss/commit/b4921645e1a899115c1a4c41d9005eced0819805
